Basic functionality
redi-js-teachers/js_sprint_2020_final_project_golovnevs pull request #7
Opened 2020-06-20 03:16 UTC by golovnevs

Hello teachers! I finished the functions for displaying the quiz and calculating the results of the quiz.  #6

2020-06-20 14:00 UTC, MrTim requested changes
Nice work! Left some comment. And please check the indentation and code structuring (functions and ifs)

Possible improvements - me as a user I would close this page after 10th click. Why? because I don't know how many steps are left and maybe it's a million. So maybe you can think of provide an info how many steps is there in the page before user starts. Just some suggestions :)

2020-06-20 14:00 UTC, MrTim commented on js/script.js
> +    }
indentation

2020-06-20 14:00 UTC, MrTim commented on js/script.js
> +  if (steps <= outfits.length-2) {
for better readability you can put spaces around `-` sign

2020-06-20 14:00 UTC, MrTim commented on js/script.js
> +  console.log(steps);
console.log)

2020-06-20 14:00 UTC, MrTim commented on js/script.js
> +    steps++;
indentation?

2020-06-20 14:00 UTC, MrTim commented on js/script.js
> +  table.innerHTML = ` <h1>Here is the most liked outfits:</h1>
```js
table.innerHTML = ` <h1>Here is the most liked outfits:</h1>`;
```
same for next row

2020-06-20 14:00 UTC, MrTim commented on js/script.js
> +function removeDuplicates() {
```js
function removeDuplicates() {
  for (let i = 0; i < liked.length; i++) {
    if (liked[i] != liked[i+1]) {
      likedUniq.push(liked[i]);
    }
  }
};
```

2020-06-20 14:00 UTC, MrTim commented on js/script.js
> +function removeDuplicates() {
And you don't need to have globally available variable `likedUniq` (and by the way there is typo - unique).
So you can remove duplicates and return it as a result from that function.

2020-06-20 14:04 UTC, MrTim commented
@golovnevs oh, and there is a bug just before you display the results
`Uncaught TypeError: Cannot read property 'addEventListener' of null`. Please check that as well.

2020-06-20 14:05 UTC, golovnevs commented on js/script.js
> +    }
Great idea, thank you! I will try to make a status bar or something like that.

2020-06-20 14:08 UTC, golovnevs commented on js/script.js
> +  console.log(steps);
Fixed :)

2020-06-20 14:10 UTC, golovnevs commented on js/script.js
> +function removeDuplicates() {
Thank you, that would be better.

2020-06-20 21:51 UTC, golovnevs commented on js/script.js
> +  if (steps <= outfits.length-2) {
Fixed.

2020-06-20 21:51 UTC, golovnevs commented on js/script.js
> +    steps++;
Fixed.

2020-06-20 22:43 UTC, golovnevs commented on js/script.js
> +function removeDuplicates() {
Fixed.

2020-06-20 22:43 UTC, golovnevs commented
@golovnevs oh, and there is a bug just before you display the results
Uncaught TypeError: Cannot read property 'addEventListener' of null. Please check that as well.

Fixed.

2020-06-20 22:45 UTC, golovnevs commented on js/script.js
> +function removeDuplicates() {
Fixed.

2020-06-20 22:47 UTC, golovnevs commented on js/script.js
> +  table.innerHTML = ` <h1>Here is the most liked outfits:</h1>
Fixed.

2020-06-20 23:07 UTC, golovnevs commented on js/script.js
> +    }
Problem with Indentation - fixed

2020-06-21 00:15 UTC, golovnevs commented on js/script.js
> +    }
Step counter added. Next step - to create animated status bar.

2020-06-21 17:26 UTC, MrTim approved these changes
Good, please merge it!

2020-06-21 17:26 UTC, MrTim commented on js/script.js
>  let totalResult =0;
space after `=` :)

2020-06-21 17:26 UTC, MrTim commented on js/script.js
> +      displayResult();
hm...indentation again different for that line

2020-06-21 20:06 UTC, golovnevs commented on js/script.js
>  let totalResult =0;
Fixed)

2020-06-21 20:06 UTC, merged